### GET request to Chat API
GET localhost:8084/chat?question="share with me the data you know already by now about me"

### Get request to redis memory
GET localhost:8084/memory/moh/chat?question="can you share with me some blog posts we wrote together?"

### GET conversations
GET localhost:8084/memory/moh/conversations

### GET conversationIds
GET localhost:8084/memory/conversations

### GET conversation-messages
GET localhost:8084/memory/moh/conversation-messages