### GET request to example server
GET http://localhost:8083

### GET using Prompt
GET http://localhost:8083/prompts


### GET popular youtubers Prompt
GET http://localhost:8083/prompts/popular?genre=programming


### GET info using instructions Prompt
GET http://localhost:8083/prompts/instruct?userInput=Tell me a Joke about Computers?


### GET songs from parser Prompt
GET http://localhost:8083/parser

### GET List of songs from parser Prompt
GET http://localhost:8083/parser/list

### GET Map of songDTO from parser Prompt
GET http://localhost:8083/parser/map

### GET List of songDTO from parser Prompt
GET http://localhost:8083/parser/dto

### GET List of songDTO using entity method
GET http://localhost:8083/parser/entity

### Get the complete response entity
GET http://localhost:8083/parser/response-entity

### Get response as stream
GET http://localhost:8083/parser/stream

### Test metadata
GET http://localhost:8083/metadata

### Test metadata using default chatClient
GET http://localhost:8083/metadata/default

### Test simple logger advisor
GET http://localhost:8083/metadata/custom-logger-advisor